In [ ]:
#Task 1
class Calculator:
  def __init__ (self):
    print("Let's Calculate!")
    self.value1 = int(input("Enter first number:"))
    self.op = input("Enter a operator:")
    self.value2 = int(input("Enter second number:"))
    if self.op == "+":
      self.add(self.value1, self.value2)
    elif self.op == "-":
      self.subtract(self.value1, self.value2)
    elif self.op == "*":
      self.multiply(self.value1, self.value2)
    elif self.op == "/":
      self.devide(self.value1, self.value2)
  def add(self,v1,v2):
    print("Value 1:", v1)
    print("Operator:", self.op)
    print("Value 2:", v2)
    print("Result:", v1 + v2)
  def subtract(self, v1, v2):
    print("Value 1:", v1)
    print("Operator:", self.op)
    print("Value 2:", v2)
    print("Result:",v1-v2)
  def multiply(self, v1, v2):
    print("Value 1:", v1)
    print("Operator:", self.op)
    print("Value 2:", v2)
    print("Result:", v1*v2)
  def devide(self, v1, v2):
    print("Value 1:", v1)
    print("Operator:", self.op)
    print("Value 2:", v2)
    print("Result:", v1/v2)
n = Calculator()

Let's Calculate!
Enter first number:7
Enter a operator:/
Enter second number:3
Value 1: 7
Operator: /
Value 2: 3
Result: 2.3333333333333335

In [ ]:
#Task 2
class Course:
  def __init__(self,c,i,s):
    self.course = c
    self.initial = i
    self.section = s
  def detail(self):
    print(self.course,"-",self.initial,"-",self.section)

c1 = Course("CSE110", "TBA", 8)
c1.detail()
print("===============")
c2 = Course("CSE111", "TBA", 9)
c2.detail()
# CSE110 - TBA - 8
# ===============
# CSE111 - TBA - 9

CSE110 - TBA - 8
===============
CSE111 - TBA - 9

In [ ]:
#Task 3
class Patient:
  def __init__(self, n, a, w, h):
    self.name = n
    self.age = a
    self.weight = w
    self.height = h
  def printDetails(self):
    print("Name:", self.name)
    print("Age:", self.age)
    print("Weight:",self.weight,"kg")
    print("Height:",self.height,"cm")
    print("BMI:", self.weight / (self.height/100)**2)
p1 = Patient("A", 55, 63.0, 158.0)
p1.printDetails()
print("====================")
p2 = Patient("B", 53, 61.0, 149.0)
p2.printDetails()
# Name: A
# Age: 55
# Weight: 63.0 kg
# Height: 158.0 cm
# BMI: 25.236340330075304
# ====================
# Name: B
# Age: 53
# Weight: 61.0 kg
# Height: 149.0 cm
# BMI: 27.476239809017613

Name: A
Age: 55
Weight: 63.0 kg
Height: 158.0 cm
BMI: 25.236340330075304
====================
Name: B
Age: 53
Weight: 61.0 kg
Height: 149.0 cm
BMI: 27.476239809017613

In [ ]:
#Task 4
class Vehicle:
  def __init__(self):
    self.car = [0,0]
  def print_position(self):
    print(tuple(self.car))
  def moveUp(self):
    self.car[1] += 1
  def moveLeft(self):
    self.car[0] -= 1
  def moveDown(self):
    self.car[1] -= 1
  def moveRight(self):
    self.car[0] += 1
car = Vehicle()
car.print_position()
car.moveUp()
car.print_position()
car.moveLeft()
car.print_position()
car.moveDown()
car.print_position()
car.moveRight()
# (0,0)
# (0,1)
# (-1,1)
# (-1,0)

(0, 0)
(0, 1)
(-1, 1)
(-1, 0)

In [ ]:
#Task 5
class Shape:
  def __init__(self, n, d1, d2):
    self.name = n
    self.dim1 = d1
    self.dim2 = d2
  def area(self):
    if self.name == 'Triangle' or self.name == 'Rhombus':
      area = 0.5*self.dim1*self.dim2
    elif self.name == 'Square' or self.name == 'Rectangle':
      area = self.dim1*self.dim2
    else:
      area = "Shape unknown"
    print("Area:",area)
triangle = Shape("Triangle",10,25)
triangle.area()
print("==========================")
square = Shape("Square",10,10)
square.area()
print("==========================")
rhombus = Shape("Rhombus",18,25)
rhombus.area()
print("==========================")
rectangle = Shape("Rectangle",15,30)
rectangle.area()
print("==========================")
trapezium = Shape("Trapezium",15,30)
trapezium.area()
# Area: 125.0
# ==========================
# Area: 100
# ==========================
# Area: 225.0
# ==========================
# Area: 450
# ==========================
# Area: Shape unknown

Area: 125.0
==========================
Area: 100
==========================
Area: 225.0
==========================
Area: 450
==========================
Area: Shape unknown

In [ ]:
#Task 6
class Calculator:
  def __init__(self):
    print("Calculator is ready!")
    self.cal = None
    self.val = 0
  def calculate(self, num1, num2, op):
    self.cal = str(num1) + " " + op + " " + str(num2)
    if op == "+":
      self.val = num1 + num2
    elif op == "-":
      self.val = num1 - num2
    elif op == "*":
      self.val = num1 * num2
    elif op == "/":
      self.val = num1 / num2
    return self.val
  def showCalculation(self):
    print(self.cal,"=",self.val)
c1 = Calculator()
print("==================")
val = c1.calculate(10, 20, '+')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 10, '-')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 5, '*')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 16, '/')
print("Returned value:", val)
c1.showCalculation()


# Calculator is ready!
# ==================
# Returned value: 30
# 10 + 20 = 30
# ==================
# Returned value: 20
# 30 - 10 = 20
# ==================
# Returned value: 100
# 20 * 5 = 100
# ==================
# Returned value: 6.25
# 100 / 16 = 6.25

Calculator is ready!
==================
Returned value: 30
10 + 20 = 30
==================
Returned value: 20
30 - 10 = 20
==================
Returned value: 100
20 * 5 = 100
==================
Returned value: 6.25
100 / 16 = 6.25

In [ ]:
#Task 7
class Student:
  def __init__(self, n, i, d, c):
    self.name = n
    self.id = i
    self.dept = d
    self.lst = c
    self.cgpa = 0
  def calculate_CGPA(self):
    for i in self.lst:
      self.cgpa += (i*3)
    self.cgpa /= (len(self.lst)*3)
  def print_details(self):
    print("Name:", self.name + ",","ID:",self.id)
    print("Department:",self.dept)
    print("CGPA:",self.cgpa)
    if self.cgpa > 3.80:
      print("Your academic standing is 'Highest Distinction'")
    elif self.cgpa > 3.65:
      print("Your academic standing is 'High Distinction'") 
    elif self.cgpa > 3.50:
      print("Your academic standing is 'Distinction'")
    elif self.cgpa > 2.00:
      print("Your academic standing is 'Satisfatory'")
    else:
      print("Sorry, you cannot graduate")

s1 = Student('Dora', '15995599','CSE', [4,3.7,3.7,4])
s1.calculate_CGPA()
print("==========================")
s1.print_details()
print("==========================")
s2 = Student('Pingu', '12312322', 'EEE', [1.7,1.3,1.3,1.3,1])
s2.calculate_CGPA()
print("==========================")
s2.print_details()
print("==========================")
s3 = Student('Bob', '13311331', 'CSE', [2,3,3,3.7,2.7,2.7])
s3.calculate_CGPA()
print("==========================")
s3.print_details()
# ==========================
# Name: Dora, ID: 15995599
# Department: CSE
# CGPA: 3.85
# Your academic standing is 'Highest
# Distinction'
# ==========================
# ==========================
# Name: Pingu, ID: 12312322
# Department: CSE
# CGPA: 1.32
# Sorry, you cannot graduate
# ==========================
# ==========================
# Name: Bob, ID: 13311331
# Department: CSE
# CGPA: 2.85
# Your academic standing is 'Satisfactory'

==========================
Name: Dora, ID: 15995599
Department: CSE
CGPA: 3.85
Your academic standing is 'Highest Distinction'
==========================
==========================
Name: Pingu, ID: 12312322
Department: EEE
CGPA: 1.32
Sorry, you cannot graduate
==========================
==========================
Name: Bob, ID: 13311331
Department: CSE
CGPA: 2.85
Your academic standing is 'Satisfatory'

In [ ]:
#Task 8
class Shinobi:
  def __init__(self, n, r):
    self.name = n
    self.rank = r
    self.salary = 0
    self.mission = 0
  def calSalary(self, m):
    self.mission = m
    if self.rank == "Genin":
      self.salary += self.mission*50
    elif self.rank == "Chunin":
      self.salary += self.mission*100
    else:
      self.salary += self.mission*500
  def printInfo(self):
    print("Name:",self.name)
    print("Rank:",self.rank)
    print("Number of mission:",self.mission)
    print("Salary:",self.salary)
  def changeRank(self, r):
    self.rank = r
naruto = Shinobi("Naruto", "Genin")
naruto.calSalary(5)
naruto.printInfo()
print('====================')
shikamaru = Shinobi('Shikamaru', "Genin")
shikamaru.printInfo()
shikamaru.changeRank("Chunin")
shikamaru.calSalary(10)
shikamaru.printInfo()
print('====================')
neiji = Shinobi("Neiji", "Jonin")
neiji.calSalary(5)
neiji.printInfo()
# Name: Naruto
# Rank: Genin
# Number of mission: 5
# Salary: 250
# ====================
# Name: Shikamaru
# Rank: Genin
# Number of mission: 0
# Salary: 0
# Name: Shikamaru
# Rank: Chunin
# Number of mission: 10
# Salary: 1000
# ====================
# Name: Neiji
# Rank: Jonin
# Number of mission: 5
# Salary: 2500

Name: Naruto
Rank: Genin
Number of mission: 5
Salary: 250
====================
Name: Shikamaru
Rank: Genin
Number of mission: 0
Salary: 0
Name: Shikamaru
Rank: Chunin
Number of mission: 10
Salary: 1000
====================
Name: Neiji
Rank: Jonin
Number of mission: 5
Salary: 2500

In [ ]:
#Task 9
class Programmer:
  def __init__(self, n, l, e):
    self.name = n
    self.lang = l
    self.exp = e
    print("Horray! A new programmer is born")
  def printDetails(self):
    print("Name:",self.name)
    print("Language:",self.lang)
    print("Experience:",self.exp,"years.")
  def addExp(self, year):
    self.exp += year
    print("Updating experience of", self.name)
p1 = Programmer("Ethen Hunt", "Java", 10)
p1.printDetails()
print('--------------------------')
p2 = Programmer("James Bond", "C++", 7)
p2.printDetails()
print('--------------------------')
p3 = Programmer("Jon Snow", "Python", 4)
p3.printDetails()
p3.addExp(5)
p3.printDetails()

# Horray! A new programmer is born
# Name: Ethen Hunt
# Language: Java
# Experience: 10 years.
# --------------------------
# Horray! A new programmer is born
# Name: James Bond
# Language: C++
# Experience: 7 years.
# --------------------------
# Horray! A new programmer is born
# Name: Jon Snow
# Language: Python
# Experience: 4 years.
# Updating experience of Jon Snow
# Name: Jon Snow
# Language: Python
# Experience: 9 years.

Horray! A new programmer is born
Name: Ethen Hunt
Language: Java
Experience: 10 years.
--------------------------
Horray! A new programmer is born
Name: James Bond
Language: C++
Experience: 7 years.
--------------------------
Horray! A new programmer is born
Name: Jon Snow
Language: Python
Experience: 4 years.
Updating experience of Jon Snow
Name: Jon Snow
Language: Python
Experience: 9 years.

In [ ]:
#Task 10
class UberEats:
  def __init__(self, n1, n2, p):
    self.name = n1
    self.num = n2
    self.place = p
    print(self.name + ",","welcome to UberEats!")
  def add_items(self,food, drink, fm, dm):
    self.order = {food: fm, drink: dm}
    self.total = fm + dm
  def print_order_detail(self):
    temp = (f"Users details: Name: {self.name}, Phone: {self.num}, Adress: {self.place} \n"
            f"Orders: {self.order}\n"
            f"Total Paid Amount: {self.total}"
    )
    return temp 

order1 = UberEats("Shakib", "01719658xxx", "Mohakhali")
print("=========================")
order1.add_items("Burger", "Coca Cola", 220, 50)
print("=========================")
print(order1.print_order_detail())

print("=========================")

order2 = UberEats ("Siam", "01719659xxx", "Uttara")
print("=========================")
order2.add_items("Pineapple", "Dairy Milk", 80, 70)
print("=========================")
print(order2.print_order_detail())
# Shakib, welcome to UberEats!
# =========================
# =========================
# User details: Name: Shakib, Phone:
# 01719658xxx, Address: Mohakhali
# Orders: {'Burger': 220, 'Coca Cola': 50}
# Total Paid Amount: 270
# =========================
# Siam, welcome to UberEats!
# =========================
# =========================
# User details: Name: Siam, Phone:
# 01719659xxx, Address: Uttara
# Orders: {'Pineapple': 80, 'Dairy Milk': 70}
# Total Paid Amount: 150

Shakib, welcome to UberEats!
=========================
=========================
Users details: Name: Shakib, Phone: 01719658xxx, Adress: Mohakhali
Orders: {'Burger': 220, 'Coca Cola': 50}
Total Paid Amount: 270
=========================
Siam, welcome to UberEats!
=========================
=========================
Users details: Name: Siam, Phone: 01719659xxx, Adress: Uttara
Orders: {'Pineapple': 80, 'Dairy Milk': 70}
Total Paid Amount: 150

In [ ]:
#Task 11
class Spotify:
  def __init__(self, s):
    self.song = s
    print("Welcome to Spotify!")
  def playing_number(self, n):
    if n <= len(self.song) and n >= 0:
      temp = "##########################\nPlaying " + str(n) + " number of song for you\n" + "Song name: " + str(self.song[n-1]) 
      #return temp
    else:
      temp = str(n) + " number song was not found. Your playlist has " + str(len(self.song)) + " songs only."
    #   temp = (f"##########################\n"
    #           f"Playing {n} number of song for you\n"
    #           f"Song name: {self.song[n-1]}"
    #   )
    # else:
    #   temp = f"{n} number song was not found. Your playlist has {len(self.song)} songs only."
#     temp = f"""{f'''##########################
# Playing {n} number song for you
# Song name: {self.song[n-1]}''' if n <= len(self.song) and n >= 0 else f'{n} number song not found. Your playlist has {len(self.song)} songs only.'}"""
    return temp
  def add_to_playlist(self, n):
    self.song.append(n)
user1 = Spotify(["See You Again", "Uptown Funk", "Hello"])
print("=========================")
print(user1.playing_number(4))
user1.add_to_playlist("Dusk Till Dawn")
print(user1.playing_number(3))
print(user1.playing_number(4))
# Welcome to Spotify!
# =========================
# 4 number song not found. Your playlist
# has 3 songs only.
# ##########################
# Playing 3 number song for you
# Song name: Hello
# ##########################
# Playing 4 number song for you
# Song name: Dusk Till Dawn

Welcome to Spotify!
=========================
4 number song was not found. Your playlist has 3 songs only.
##########################
Playing 3 number of song for you
Song name: Hello
##########################
Playing 4 number of song for you
Song name: Dusk Till Dawn

In [ ]:
class Test5:
  def __init__(self):
    self.sum, self.y = 0, 0
  def methodA(self):
    x = 0
    z = 0
    while (z < 5):
      self.y = self.y + self.sum
      x = self.y + 1
      print(x, self.y, self.sum) 
      self.sum = self.sum + self.methodB(x, self.y)
      z += 1
  def methodB(self, m, n):
    x = 0
    sum = 0
    self.y = self.y + m
    x = n - 4
    sum = sum + self.y
    print(x, self.y, sum)
    return self.sum
t5 = Test5()
t5.methodA()

1 0 0
-4 1 1
2 1 0
-3 3 3
4 3 0
-1 7 7
8 7 0
3 15 15
16 15 0
11 31 31

In [ ]:
lst = [1,2,3,4,3,4,3,4,2,4,2,4]
print(lst[: :-1])

[4, 2, 4, 2, 4, 3, 4, 3, 4, 3, 2, 1]